### PR TITLE
PAT References

### PR DESCRIPTION
**Pull request by ShyamSundhar1411**

### CODE REVIEW

**Comment by AbhijithGanesh** [comment]
Please add the question in a .md file

**Comment by ShyamSundhar1411** [comment]
OK then but I am not having the question

**Comment by AbhijithGanesh** [comment]
Sure, I will figure it out and add it

**Comment by ShyamSundhar1411** [comment]
Send me the qs Please

**Comment by AbhijithGanesh** [comment]
I think there is a lot of extra space used (variable names) and it is not optimized, I will send the algorithm and you can add it to our .md file and make it more solid

**Comment by AbhijithGanesh** [comment]
Question:

```
Given a list/array of n numbers, the sum of numbers are taken from left to right and right to left, Find the element common to both sums and print the common element. Apart from this print the sums from left and right
```

**Comment by AbhijithGanesh** [comment]
I will be committing the Algorithm and then we'll discuss the optimization

**Pull request merged**
